# Generated by Django 5.2.7 on 2026-02-19 14:26

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('level', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='products.category')),
            ],
            options={
                'verbose_name': 'Category (ճյուղ)',
                'verbose_name_plural': 'Categories (ճյուղեր)',
            },
        ),
        migrations.CreateModel(
            name='CategoryAttribute',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('data_type', models.CharField(choices=[('string', 'Text (տեքստ)'), ('number', 'Number (թիվ)'), ('boolean', 'Yes/No (այո/ոչ)'), ('select', 'Select (ընտրություն)')], max_length=20)),
                ('is_required', models.BooleanField(default=False)),
                ('unit', models.CharField(blank=True, max_length=50, null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attributes', to='products.category')),
            ],
            options={
                'verbose_name': 'Category Attribute (ճյուղային պարամետր)',
                'verbose_name_plural': 'Category Attributes (ճյուղային պարամետրեր)',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('manufacturer', models.CharField(max_length=255)),
                ('model_number', models.CharField(blank=True, max_length=255, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='products.category')),
            ],
            options={
                'verbose_name': 'Product (ապրանք)',
                'verbose_name_plural': 'Products (ապրանքներ)',
            },
        ),
        migrations.CreateModel(
            name='AttributeRange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_value', models.FloatField()),
                ('max_value', models.FloatField()),
                ('attribute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ranges', to='products.categoryattribute')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ranges', to='products.product')),
            ],
            options={
                'verbose_name': 'Attribute Range (Attribute-ի միջակայք)',
                'verbose_name_plural': 'Attribute Ranges (Attribute-ների միջակայքներ)',
            },
        ),
        migrations.CreateModel(
            name='ProductAttributeValue',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('value', models.CharField(max_length=255)),
                ('attribute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.categoryattribute')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attribute_values', to='products.product')),
            ],
            options={
                'verbose_name': 'Product Attribute Value (ապրանքի պարամետրերի արժեք)',
                'verbose_name_plural': 'Product Attribute Values (ապրանքների պարամետրերի արժեքներ)',
            },
        ),
    ]
