# Generated by Django 5.2.7 on 2026-03-03 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_categorycomponentgroup_categorycomponent_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={},
        ),
        migrations.AddField(
            model_name='product',
            name='artikul',
            field=models.CharField(default=1, editable=False, max_length=20, unique=True, verbose_name='Արտիկուլ'),
            preserve_default=False,
        ),
    ]
