# Generated by Django 5.2.7 on 2026-03-03 12:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0020_importerprofile_id_card_number'),
        ('products', '0003_alter_product_options_product_artikul'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='country_of_manufacture',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='currency',
            field=models.CharField(default='AMD', max_length=3),
        ),
        migrations.AddField(
            model_name='product',
            name='gmx_standard_value',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='importer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='accounts.importerprofile'),
        ),
        migrations.AddField(
            model_name='product',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
    ]
