# Generated by Django 5.2.7 on 2026-03-03 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_product_country_of_manufacture_product_currency_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='gmx_standard_value',
        ),
        migrations.AddField(
            model_name='product',
            name='standardisation_code',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Կատեգորիայի կոդ'),
        ),
    ]
