# Generated by Django 5.2.7 on 2026-03-04 22:24

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_productmedia_delete_productimage_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryAttributeType',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'verbose_name': 'Attribute Type (Պարամետրի տեսակ)',
                'verbose_name_plural': 'Attribute Types (Պարամետրերի տեսակներ)',
            },
        ),
        migrations.AlterModelOptions(
            name='categoryattribute',
            options={},
        ),
        migrations.AddField(
            model_name='categoryattribute',
            name='attribute_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attributes', to='products.categoryattributetype'),
        ),
    ]
