# Generated by Django 5.2.7 on 2026-03-16 16:50

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_categoryattributetype_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductAttribute',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('data_type', models.CharField(choices=[('string', 'Text (տեքստ)'), ('number', 'Number (թիվ)'), ('boolean', 'Yes/No (այո/ոչ)'), ('select', 'Select (ընտրություն)')], max_length=20)),
                ('is_required', models.BooleanField(default=False)),
                ('unit', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('attribute_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product_attributes', to='products.categoryattributetype')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_attributes', to='products.product')),
            ],
            options={
                'verbose_name': 'Product Attribute (Ապրանքի անհատական պարամետր)',
                'verbose_name_plural': 'Product Attributes (Ապրանքների անհատական պարամետրեր)',
                'unique_together': {('product', 'name')},
            },
        ),
        migrations.CreateModel(
            name='ProductCustomAttributeValue',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('value', models.CharField(max_length=255)),
                ('attribute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='values', to='products.productattribute')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_attribute_values', to='products.product')),
            ],
            options={
                'verbose_name': 'Product Custom Attribute Value (Ապրանքի անհատական պարամետրի արժեք)',
                'verbose_name_plural': 'Product Custom Attribute Values (Ապրանքների անհատական պարամետրերի արժեքներ)',
                'unique_together': {('product', 'attribute')},
            },
        ),
    ]
