# Generated by Django 5.2.7 on 2026-03-16 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_productattribute_productcustomattributevalue'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categoryattribute',
            options={'verbose_name': 'Category Attribute (Կատեգորիայի պարամետր)', 'verbose_name_plural': 'Category Attributes (Կատեգորիայի պարամետրեր)'},
        ),
        migrations.AlterModelOptions(
            name='productattributevalue',
            options={'verbose_name': 'Product Attribute Value', 'verbose_name_plural': 'Product Attribute Values'},
        ),
        migrations.AddField(
            model_name='categoryattribute',
            name='is_main_filter',
            field=models.BooleanField(default=False, verbose_name='Հիմնական ֆիլտր'),
        ),
        migrations.AddField(
            model_name='product',
            name='artikul_number',
            field=models.PositiveIntegerField(blank=True, editable=False, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='productattribute',
            name='is_main_filter',
            field=models.BooleanField(default=False, verbose_name='Հիմնական ֆիլտր'),
        ),
        migrations.AlterField(
            model_name='product',
            name='artikul',
            field=models.CharField(blank=True, editable=False, max_length=20, unique=True, verbose_name='Արտիկուլ'),
        ),
        migrations.AlterField(
            model_name='product',
            name='standardisation_code',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='productmedia',
            name='media_type',
            field=models.CharField(blank=True, choices=[('image', 'Image'), ('video', 'Video')], max_length=10),
        ),
    ]
