# Generated by Django 5.2.7 on 2026-03-18 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_alter_categoryattribute_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='artikul',
            field=models.CharField(blank=True, editable=False, max_length=20, verbose_name='Արտիկուլ'),
        ),
        migrations.AlterField(
            model_name='product',
            name='artikul_number',
            field=models.PositiveIntegerField(blank=True, editable=False, null=True),
        ),
    ]
