# Generated by Django 5.2.7 on 2026-03-28 23:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_remove_product_manufacturer_product_brand'),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('code', models.CharField(blank=True, max_length=10, null=True, unique=True)),
            ],
            options={
                'verbose_name': 'Country (Երկիր)',
                'verbose_name_plural': 'Countries (Երկրներ)',
                'ordering': ['name'],
            },
        ),
        migrations.AlterField(
            model_name='product',
            name='country_of_manufacture',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='products', to='products.country'),
        ),
    ]
