# Generated by Django 5.2.7 on 2026-03-28 23:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_country_alter_product_country_of_manufacture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='country_of_manufacture',
        ),
    ]
