# Generated by Django 5.2.7 on 2026-03-28 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0014_remove_product_country_of_manufacture'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='country_of_manufacture',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
