# Generated by Django 5.2.7 on 2026-03-28 23:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0015_product_country_of_manufacture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='country_of_manufacture',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='products', to='products.country'),
        ),
    ]
