# Generated by Django 5.2.7 on 2026-03-28 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0017_rename_price_product_price_max_product_price_min'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoryattributetype',
            name='is_filterable',
            field=models.BooleanField(default=False, verbose_name='Ֆիլտրացիայի համար'),
        ),
    ]
