# Generated by Django 5.2.7 on 2026-03-29 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0018_categoryattributetype_is_filterable'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoryattribute',
            name='default_value',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Բազային արժեք'),
        ),
        migrations.AddField(
            model_name='categoryattribute',
            name='has_default_value',
            field=models.BooleanField(default=False, verbose_name='Բազային արժեք ունի'),
        ),
        migrations.AddField(
            model_name='categoryattribute',
            name='value_help_url',
            field=models.URLField(blank=True, null=True, verbose_name='Արժեքների հղում'),
        ),
    ]
