# Generated by Django 5.2.7 on 2026-03-29 05:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0019_categoryattribute_default_value_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productcustomattributevalue',
            options={'verbose_name': 'Product Custom Attribute Value', 'verbose_name_plural': 'Product Custom Attribute Values'},
        ),
        migrations.RemoveField(
            model_name='productattributevalue',
            name='value',
        ),
        migrations.RemoveField(
            model_name='productcustomattributevalue',
            name='value',
        ),
        migrations.AddField(
            model_name='productattributevalue',
            name='value_boolean',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='productattributevalue',
            name='value_number',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='productattributevalue',
            name='value_text',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='productcustomattributevalue',
            name='value_boolean',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='productcustomattributevalue',
            name='value_number',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='productcustomattributevalue',
            name='value_text',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.CreateModel(
            name='AttributeChoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=255)),
                ('attribute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='products.categoryattribute')),
            ],
        ),
        migrations.CreateModel(
            name='ProductAttributeChoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=255)),
                ('attribute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='products.productattribute')),
            ],
        ),
    ]
