# Generated by Django 5.2.7 on 2026-03-29 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0020_alter_productcustomattributevalue_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='status',
            field=models.CharField(choices=[('available', 'Առկա է'), ('unavailable', 'Առկա չէ'), ('on_order', 'Պատվերով')], default='available', max_length=20, verbose_name='Պրոդուկտի ստատուս'),
        ),
    ]
