# Generated by Django 5.2.7 on 2026-04-04 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0021_product_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Կարճ նկարագրություն'),
        ),
        migrations.AddField(
            model_name='category',
            name='help_url',
            field=models.URLField(blank=True, null=True, verbose_name='Լրիվ բացատրության հղում'),
        ),
        migrations.AddField(
            model_name='categoryattributetype',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Կարճ նկարագրություն'),
        ),
        migrations.AddField(
            model_name='categoryattributetype',
            name='help_url',
            field=models.URLField(blank=True, null=True, verbose_name='Լրիվ բացատրության հղում'),
        ),
    ]
