# Generated by Django 5.2.7 on 2026-04-05 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0022_category_description_category_help_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoryattribute',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Կարճ նկարագրություն'),
        ),
    ]
