# Generated by Django 5.2.7 on 2026-04-15 03:55

import django.db.models.deletion
import django_ckeditor_5.fields
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0023_categoryattribute_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='description',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True, verbose_name='Ապրանքի նկարագրություն'),
        ),
        migrations.CreateModel(
            name='ProductCertificate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=255, null=True, verbose_name='Վերնագիր')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Կարճ նկարագրություն')),
                ('file', models.FileField(upload_to='products/certificates/', verbose_name='Սերտիֆիկատ')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificates', to='products.product')),
            ],
            options={
                'verbose_name': 'Product Certificate (Ապրանքի սերտիֆիկատ)',
                'verbose_name_plural': 'Product Certificates (Ապրանքի սերտիֆիկատներ)',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProductDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=255, null=True, verbose_name='Վերնագիր')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Կարճ նկարագրություն')),
                ('file', models.FileField(upload_to='products/documents/', verbose_name='Փաստաթուղթ')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='products.product')),
            ],
            options={
                'verbose_name': 'Product Document (Ապրանքի փաստաթուղթ)',
                'verbose_name_plural': 'Product Documents (Ապրանքի փաստաթղթեր)',
                'ordering': ['-created_at'],
            },
        ),
    ]
