# Generated by Django 5.2.7 on 2026-01-30 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_healthcarefacility_importer_delete_tempregistration_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TempRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_type', models.CharField(choices=[('worker', 'Healthcare Worker'), ('facility', 'Healthcare Facility'), ('importer', 'Importer / Manufacturer')], max_length=20)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('password', models.CharField(blank=True, max_length=255, null=True)),
                ('is_active', models.BooleanField(default=False)),
                ('email_verified', models.BooleanField(default=False)),
                ('first_name', models.CharField(blank=True, max_length=100, null=True)),
                ('last_name', models.CharField(blank=True, max_length=100, null=True)),
                ('father_name', models.CharField(blank=True, max_length=100, null=True)),
                ('birth_year', models.IntegerField(blank=True, null=True)),
                ('birth_month', models.IntegerField(blank=True, null=True)),
                ('birth_day', models.IntegerField(blank=True, null=True)),
                ('facility_name', models.CharField(blank=True, max_length=255, null=True)),
                ('contact_first_name', models.CharField(blank=True, max_length=100, null=True)),
                ('contact_last_name', models.CharField(blank=True, max_length=100, null=True)),
                ('company_name', models.CharField(blank=True, max_length=255, null=True)),
                ('contact_first_name_importer', models.CharField(blank=True, max_length=100, null=True)),
                ('contact_last_name_importer', models.CharField(blank=True, max_length=100, null=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='healthcareworker',
            name='user',
        ),
        migrations.RemoveField(
            model_name='importer',
            name='user',
        ),
        migrations.DeleteModel(
            name='HealthcareFacility',
        ),
        migrations.DeleteModel(
            name='HealthcareWorker',
        ),
        migrations.DeleteModel(
            name='Importer',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
