# Generated by Django 5.2.7 on 2026-01-31 04:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_tempregistration_remove_healthcareworker_user_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_type', models.CharField(choices=[('worker', 'Healthcare Worker'), ('facility', 'Healthcare Facility'), ('importer', 'Importer / Manufacturer')], max_length=20)),
                ('phone', models.CharField(max_length=20)),
                ('email_verified', models.BooleanField(default=False)),
                ('is_verified', models.BooleanField(default=False)),
                ('father_name', models.CharField(blank=True, max_length=100, null=True)),
                ('birth_year', models.IntegerField(blank=True, null=True)),
                ('birth_month', models.IntegerField(blank=True, null=True)),
                ('birth_day', models.IntegerField(blank=True, null=True)),
                ('facility_name', models.CharField(blank=True, max_length=255, null=True)),
                ('contact_first_name', models.CharField(blank=True, max_length=100, null=True)),
                ('contact_last_name', models.CharField(blank=True, max_length=100, null=True)),
                ('company_name', models.CharField(blank=True, max_length=255, null=True)),
                ('contact_first_name_importer', models.CharField(blank=True, max_length=100, null=True)),
                ('contact_last_name_importer', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='TempRegistration',
        ),
    ]
