# Generated by Django 5.2.7 on 2026-01-31 04:56

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_remove_userprofile_contact_first_name_importer_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='birth_day',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='birth_month',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='birth_year',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='company_name',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='contact_first_name',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='contact_last_name',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='email_verified',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='facility_name',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='father_name',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='is_verified',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='phone',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user_type',
            field=models.CharField(choices=[('worker', 'Healthcare Worker'), ('facility', 'Healthcare Facility'), ('importer', 'Importer')], max_length=20),
        ),
    ]
