# Generated by Django 5.2.7 on 2026-02-01 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_remove_userprofile_created_at_userprofile_birth_day_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='birth_day',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='birth_month',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='birth_year',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='company_name',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='contact_first_name',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='contact_first_name_importer',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='contact_last_name',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='contact_last_name_importer',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='email_verified',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='facility_name',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='father_name',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='phone',
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user_type',
            field=models.CharField(choices=[('worker', 'Աշխատող'), ('facility', 'Հասարակական կենտրոն'), ('importer', 'Ներմատակարար')], max_length=20),
        ),
    ]
