# Generated by Django 5.2.7 on 2026-02-09 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_facilityprofile_is_approved_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facilityprofile',
            name='is_verified',
            field=models.BooleanField(default=False, verbose_name='Հաստատված է (SMS / Email)'),
        ),
        migrations.AlterField(
            model_name='importerprofile',
            name='is_verified',
            field=models.BooleanField(default=False, verbose_name='Հաստատված է (SMS / Email)'),
        ),
        migrations.AlterField(
            model_name='workerprofile',
            name='is_verified',
            field=models.BooleanField(default=False, verbose_name='Հաստատված է (SMS / Email)'),
        ),
    ]
