# Generated by Django 5.2.7 on 2026-02-09 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_alter_facilityprofile_is_verified_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facilityprofile',
            name='is_approved',
            field=models.BooleanField(default=False, verbose_name='Գործունեությունը թույլադրված է '),
        ),
        migrations.AlterField(
            model_name='facilityprofile',
            name='is_verified',
            field=models.BooleanField(default=False, verbose_name='էլ-հասցեն հաստատված է '),
        ),
        migrations.AlterField(
            model_name='importerprofile',
            name='is_approved',
            field=models.BooleanField(default=False, verbose_name='Գործունեությունը թույլադրված է '),
        ),
        migrations.AlterField(
            model_name='importerprofile',
            name='is_verified',
            field=models.BooleanField(default=False, verbose_name='էլ-հասցեն հաստատված է '),
        ),
        migrations.AlterField(
            model_name='workerprofile',
            name='is_approved',
            field=models.BooleanField(default=False, verbose_name='Գործունեությունը թույլադրված է '),
        ),
        migrations.AlterField(
            model_name='workerprofile',
            name='is_verified',
            field=models.BooleanField(default=False, verbose_name='էլ-հասցեն հաստատված է '),
        ),
    ]
