# Generated by Django 5.2.7 on 2026-02-10 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_alter_facilityprofile_is_approved_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='workerprofile',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Հասցե'),
        ),
        migrations.AddField(
            model_name='workerprofile',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='workerprofile',
            name='documents',
            field=models.FileField(blank=True, null=True, upload_to='worker_documents/', verbose_name='Փաստաթղթեր'),
        ),
        migrations.AddField(
            model_name='workerprofile',
            name='id_card_number',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='ID քարտի համար'),
        ),
        migrations.AddField(
            model_name='workerprofile',
            name='license_number',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Լիցենզիայի համար'),
        ),
        migrations.AddField(
            model_name='workerprofile',
            name='profile_photo',
            field=models.ImageField(blank=True, null=True, upload_to='worker_photos/', verbose_name='Նկար'),
        ),
        migrations.AddField(
            model_name='workerprofile',
            name='specialization',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Մասնագիտություն'),
        ),
        migrations.AddField(
            model_name='workerprofile',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='workerprofile',
            name='verification_status',
            field=models.CharField(blank=True, choices=[('pending', 'Ընթացքի մեջ'), ('approved', 'Հաստատված է'), ('rejected', 'Մերժված է')], max_length=20, null=True, verbose_name='Վերիֆիկացիայի ստատուս'),
        ),
        migrations.AddField(
            model_name='workerprofile',
            name='verified_by',
            field=models.CharField(blank=True, choices=[('admin', 'Ադմին'), ('registry', 'Պետական ռեգիստր'), ('external', 'Արտաքին աղբյուր')], max_length=20, null=True, verbose_name='Վերիֆիկացրել է'),
        ),
        migrations.AddField(
            model_name='workerprofile',
            name='workplaces',
            field=models.TextField(blank=True, null=True, verbose_name='Աշխատանքի վայրեր'),
        ),
    ]
