# Generated by Django 5.2.7 on 2026-02-10 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_facilityprofile_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='importerprofile',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='importerprofile',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='importer_logos/', verbose_name='Լոգո'),
        ),
        migrations.AddField(
            model_name='importerprofile',
            name='registration_documents',
            field=models.FileField(blank=True, null=True, upload_to='importer_documents/', verbose_name='Գրանցման / լիցենզիայի փաստաթղթեր'),
        ),
        migrations.AddField(
            model_name='importerprofile',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='importerprofile',
            name='verification_status',
            field=models.CharField(blank=True, choices=[('pending', 'Ընթացքի մեջ'), ('approved', 'Հաստատված է'), ('rejected', 'Մերժված է')], max_length=20, null=True, verbose_name='Վերիֆիկացիայի ստատուս'),
        ),
        migrations.AddField(
            model_name='importerprofile',
            name='verified_by',
            field=models.CharField(blank=True, choices=[('admin', 'Ադմին'), ('registry', 'Պետական ռեգիստր'), ('external', 'Արտաքին աղբյուր')], max_length=20, null=True, verbose_name='Վերիֆիկացրել է'),
        ),
    ]
