# Generated by Django 5.2.7 on 2026-02-15 11:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_importerprofile_created_at_importerprofile_logo_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='facilityprofile',
            name='fac_address',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='facilityprofile',
            name='factory_license_number',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='facilityprofile',
            name='father_name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_read', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
