# Generated by Django 5.2.7 on 2026-02-15 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_facilityprofile_fac_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='facilityprofile',
            name='id_card_number',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='ID քարտի համար'),
        ),
    ]
