# Generated by Django 5.2.7 on 2026-02-15 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_facilityprofile_id_card_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='importerprofile',
            name='id_card_number',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='ID քարտի համար'),
        ),
    ]
