# Generated by Django 5.2.7 on 2026-03-16 19:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0020_importerprofile_id_card_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='FacilityWorkPhone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=20, verbose_name='Աշխատանքային հեռախոսահամար')),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_phones', to='accounts.facilityprofile')),
            ],
        ),
        migrations.CreateModel(
            name='ImporterWorkPhone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=20, verbose_name='Աշխատանքային հեռախոսահամար')),
                ('importer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_phones', to='accounts.importerprofile')),
            ],
        ),
    ]
