# Generated by Django 5.2.7 on 2026-03-28 13:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0021_facilityworkphone_importerworkphone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='importerprofile',
            name='registration_documents',
        ),
        migrations.AddField(
            model_name='importerprofile',
            name='is_certified',
            field=models.BooleanField(default=False, verbose_name='Սերտիֆիկացված է'),
        ),
        migrations.AlterField(
            model_name='importerprofile',
            name='verification_status',
            field=models.CharField(blank=True, choices=[('pending', 'Ընթացքի մեջ'), ('approved', 'Հաստատված է'), ('rejected', 'Մերժված է')], default='pending', max_length=20, null=True, verbose_name='Վերիֆիկացիայի ստատուս'),
        ),
        migrations.CreateModel(
            name='ImporterCertificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Սերտիֆիկատի անուն')),
                ('file', models.FileField(blank=True, null=True, upload_to='importer_certificates/', verbose_name='Ֆայլ / Նկար')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('importer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificates', to='accounts.importerprofile')),
            ],
        ),
    ]
