# Generated by Django 5.2.7 on 2026-03-28 18:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0022_remove_importerprofile_registration_documents_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImporterContract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Պայմանագրի անուն')),
                ('file', models.FileField(blank=True, null=True, upload_to='importer_contracts/', verbose_name='Պայմանագրի ֆայլ')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('importer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contracts', to='accounts.importerprofile')),
            ],
        ),
    ]
