# Generated by Django 5.2.7 on 2026-03-28 19:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0023_importercontract'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImporterParameter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('value_type', models.CharField(choices=[('text', 'Տեքստ'), ('number', 'Թիվ'), ('choice', 'Ընտրովի'), ('file', 'Ֆայլ'), ('image', 'Նկար'), ('video', 'Վիդեո')], default='text', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='ImporterParameterType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ImporterParameterChoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=255)),
                ('parameter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='accounts.importerparameter')),
            ],
        ),
        migrations.AddField(
            model_name='importerparameter',
            name='parameter_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parameters', to='accounts.importerparametertype'),
        ),
        migrations.CreateModel(
            name='ImporterParameterValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_value', models.TextField(blank=True, null=True)),
                ('number_value', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('file_value', models.FileField(blank=True, null=True, upload_to='param_files/')),
                ('image_value', models.ImageField(blank=True, null=True, upload_to='param_images/')),
                ('video_value', models.FileField(blank=True, null=True, upload_to='param_videos/')),
                ('choice_value', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.importerparameterchoice')),
                ('importer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parameter_values', to='accounts.importerprofile')),
                ('parameter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='importer_values', to='accounts.importerparameter')),
            ],
        ),
    ]
