# Generated by Django 5.2.7 on 2026-03-28 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0024_importerparameter_importerparametertype_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='importerparametervalue',
            name='boolean_value',
            field=models.BooleanField(blank=True, choices=[(True, 'Առկա է'), (False, 'Առկա չէ')], null=True, verbose_name='Առկա է / Առկա չէ'),
        ),
        migrations.AlterField(
            model_name='importerparameter',
            name='value_type',
            field=models.CharField(choices=[('text', 'Տեքստ'), ('number', 'Թիվ'), ('choice', 'Ընտրովի'), ('file', 'Ֆայլ'), ('image', 'Նկար'), ('video', 'Վիդեո'), ('boolean', 'Առկա է / Առկա չէ')], default='text', max_length=20),
        ),
    ]
