# Generated by Django 5.2.7 on 2026-03-28 21:01

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0025_importerparametervalue_boolean_value_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Բրենդի անուն')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='brand_logos/', verbose_name='Լոգո')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ակտիվ է')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='importerprofile',
            name='brands',
            field=models.ManyToManyField(blank=True, related_name='importers', to='accounts.brand', verbose_name='Ներկայացվող բրենդեր'),
        ),
    ]
