# Generated by Django 5.2.7 on 2026-03-28 21:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0026_brand_importerprofile_brands'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='brand',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='importerprofile',
            name='brands',
        ),
        migrations.AddField(
            model_name='brand',
            name='importer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='brands', to='accounts.importerprofile', verbose_name='Մատակարար'),
        ),
        migrations.AlterField(
            model_name='brand',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Բրենդ'),
        ),
    ]
