# Generated by Django 5.2.7 on 2026-03-28 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0027_remove_brand_is_active_remove_importerprofile_brands_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='brand',
            name='importer',
        ),
        migrations.AlterField(
            model_name='brand',
            name='name',
            field=models.CharField(max_length=255, unique=True, verbose_name='Բրենդ'),
        ),
    ]
