# Generated by Django 5.2.7 on 2026-03-28 21:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0028_remove_brand_importer_alter_brand_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImporterBrand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='brand_importers', to='accounts.brand', verbose_name='Բրենդ')),
                ('importer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='importer_brands', to='accounts.importerprofile', verbose_name='Մատակարար')),
            ],
            options={
                'unique_together': {('importer', 'brand')},
            },
        ),
    ]
