# Generated by Django 5.2.7 on 2026-04-06 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0029_importerbrand'),
    ]

    operations = [
        migrations.AddField(
            model_name='importerparameter',
            name='is_filterable',
            field=models.BooleanField(default=False),
        ),
    ]
