# Generated by Django 5.2.7 on 2026-04-11 22:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0030_importerparameter_is_filterable'),
    ]

    operations = [
        migrations.CreateModel(
            name='BrandInfoType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Ինֆոյի տեսակ')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='Տեխնիկական key')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Բրենդի ինֆոյի տեսակ',
                'verbose_name_plural': 'Բրենդի ինֆոյի տեսակներ',
                'ordering': ['name'],
            },
        ),
        migrations.AlterModelOptions(
            name='importerbrand',
            options={'verbose_name': 'Մատակարար - Բրենդ կապ', 'verbose_name_plural': 'Մատակարար - Բրենդ կապեր'},
        ),
        migrations.CreateModel(
            name='BrandMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media_type', models.CharField(choices=[('image', 'Նկար'), ('video', 'Վիդեո')], max_length=20, verbose_name='Մեդիայի տեսակ')),
                ('title', models.CharField(blank=True, max_length=255, null=True, verbose_name='Անվանում')),
                ('file', models.FileField(upload_to='brand_media/', verbose_name='Ֆայլ')),
                ('preview_image', models.ImageField(blank=True, null=True, upload_to='brand_media_previews/', verbose_name='Preview նկար')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Հերթականություն')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ակտիվ է')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media_items', to='accounts.brand', verbose_name='Բրենդ')),
            ],
            options={
                'verbose_name': 'Բրենդի մեդիա',
                'verbose_name_plural': 'Բրենդի մեդիաներ',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='BrandInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.SlugField(max_length=255, verbose_name='Տեխնիկական key / id')),
                ('name', models.CharField(max_length=255, verbose_name='Անվանում')),
                ('value', models.TextField(verbose_name='Արժեք')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Հերթականություն')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ակտիվ է')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='info_items', to='accounts.brand', verbose_name='Բրենդ')),
                ('info_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='brand_infos', to='accounts.brandinfotype', verbose_name='Ինֆոյի տեսակ')),
            ],
            options={
                'verbose_name': 'Բրենդի ինֆո',
                'verbose_name_plural': 'Բրենդի ինֆոներ',
                'ordering': ['info_type', 'order', 'id'],
                'unique_together': {('brand', 'info_type', 'key')},
            },
        ),
    ]
