# Generated by Django 5.2.7 on 2026-04-12 19:06

import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0031_brandinfotype_alter_importerbrand_options_brandmedia_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='brandmedia',
            name='brand',
        ),
        migrations.AlterUniqueTogether(
            name='importerbrand',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='importerbrand',
            name='brand',
        ),
        migrations.RemoveField(
            model_name='importerbrand',
            name='importer',
        ),
        migrations.AlterModelOptions(
            name='brand',
            options={'ordering': ['order', 'name'], 'verbose_name': 'Բրենդ', 'verbose_name_plural': 'Բրենդներ'},
        ),
        migrations.AddField(
            model_name='brand',
            name='country',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Երկիր'),
        ),
        migrations.AddField(
            model_name='brand',
            name='founded_year',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Հիմնադրման տարեթիվ'),
        ),
        migrations.AddField(
            model_name='brand',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Ակտիվ է'),
        ),
        migrations.AddField(
            model_name='brand',
            name='main_info',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True, verbose_name='Հիմնական ինֆո (երկար տեքստ)'),
        ),
        migrations.AddField(
            model_name='brand',
            name='order',
            field=models.PositiveIntegerField(default=0, verbose_name='Հերթականություն'),
        ),
        migrations.AddField(
            model_name='brand',
            name='seo_description',
            field=models.TextField(blank=True, null=True, verbose_name='SEO նկարագրություն'),
        ),
        migrations.AddField(
            model_name='brand',
            name='seo_title',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='SEO վերնագիր'),
        ),
        migrations.AddField(
            model_name='brand',
            name='short_info',
            field=models.TextField(blank=True, null=True, verbose_name='Կարճ ինֆո'),
        ),
        migrations.AddField(
            model_name='brand',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, null=True, unique=True, verbose_name='Slug'),
        ),
        migrations.AddField(
            model_name='brand',
            name='websites',
            field=models.JSONField(blank=True, default=list, verbose_name='Կայքերի հղումներ'),
        ),
        migrations.AlterField(
            model_name='brand',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Ստեղծվել է'),
        ),
        migrations.AlterField(
            model_name='brand',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Թարմացվել է'),
        ),
        migrations.DeleteModel(
            name='BrandInfo',
        ),
        migrations.DeleteModel(
            name='BrandInfoType',
        ),
        migrations.DeleteModel(
            name='BrandMedia',
        ),
        migrations.DeleteModel(
            name='ImporterBrand',
        ),
    ]
