# Generated by Django 5.2.7 on 2026-04-12 19:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0032_remove_brandmedia_brand_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BrandMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media_type', models.CharField(choices=[('image', 'Նկար'), ('video', 'Վիդեո')], max_length=20, verbose_name='Մեդիայի տեսակ')),
                ('title', models.CharField(blank=True, max_length=255, null=True, verbose_name='Անվանում')),
                ('file', models.FileField(upload_to='brand_media/', verbose_name='Ֆայլ')),
                ('preview_image', models.ImageField(blank=True, null=True, upload_to='brand_media_previews/', verbose_name='Preview նկար')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Հերթականություն')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ակտիվ է')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Ստեղծվել է')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media_items', to='accounts.brand', verbose_name='Բրենդ')),
            ],
            options={
                'verbose_name': 'Բրենդի մեդիա',
                'verbose_name_plural': 'Բրենդի մեդիաներ',
                'ordering': ['order', 'id'],
            },
        ),
    ]
