# Generated by Django 5.2.7 on 2026-04-12 20:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0033_brandmedia'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImporterBrand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='brand_importers', to='accounts.brand')),
                ('importer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='importer_brands', to='accounts.importerprofile')),
            ],
        ),
    ]
