# Generated by Django 5.2.7 on 2026-04-12 22:44

import django.db.models.deletion
import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0034_importerbrand'),
    ]

    operations = [
        migrations.AddField(
            model_name='importerprofile',
            name='address',
            field=models.TextField(blank=True, null=True, verbose_name='Հասցե'),
        ),
        migrations.AddField(
            model_name='importerprofile',
            name='city',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Քաղաք'),
        ),
        migrations.AddField(
            model_name='importerprofile',
            name='country',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Երկիր'),
        ),
        migrations.AddField(
            model_name='importerprofile',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Էլ. հասցե'),
        ),
        migrations.AddField(
            model_name='importerprofile',
            name='founded_year',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Հիմնադրման տարեթիվ'),
        ),
        migrations.AddField(
            model_name='importerprofile',
            name='main_info',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True, verbose_name='Հիմնական ինֆո'),
        ),
        migrations.AddField(
            model_name='importerprofile',
            name='short_info',
            field=models.TextField(blank=True, null=True, verbose_name='Կարճ ինֆո'),
        ),
        migrations.AddField(
            model_name='importerprofile',
            name='websites',
            field=models.JSONField(blank=True, default=list, verbose_name='Կայքեր / սոցցանցեր'),
        ),
        migrations.AlterField(
            model_name='importerprofile',
            name='is_approved',
            field=models.BooleanField(default=False, verbose_name='Գործունեությունը թույլադրված է'),
        ),
        migrations.AlterField(
            model_name='importerprofile',
            name='is_verified',
            field=models.BooleanField(default=False, verbose_name='էլ-հասցեն հաստատված է'),
        ),
        migrations.CreateModel(
            name='ImporterEmployee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Անուն')),
                ('position', models.CharField(max_length=255, verbose_name='Մասնագիտություն / Պաշտոն')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='importer_employees/', verbose_name='Նկար')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Հերթականություն')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ակտիվ է')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('importer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employees', to='accounts.importerprofile', verbose_name='Մատակարար')),
            ],
            options={
                'verbose_name': 'Մատակարարի աշխատող',
                'verbose_name_plural': 'Մատակարարի աշխատողներ',
                'ordering': ['order', 'id'],
            },
        ),
    ]
