# Generated by Django 5.2.7 on 2026-04-14 11:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0035_importerprofile_address_importerprofile_city_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='importercertificate',
            options={'ordering': ['-created_at', 'id'], 'verbose_name': 'Սերտիֆիկատ', 'verbose_name_plural': 'Սերտիֆիկատներ'},
        ),
        migrations.AlterModelOptions(
            name='importercontract',
            options={'ordering': ['-created_at', 'id'], 'verbose_name': 'Պայմանագիր', 'verbose_name_plural': 'Պայմանագրեր'},
        ),
        migrations.AlterModelOptions(
            name='importerparameter',
            options={'ordering': ['parameter_type__name', 'name'], 'verbose_name': 'Պարամետր', 'verbose_name_plural': 'Պարամետրեր'},
        ),
        migrations.AlterModelOptions(
            name='importerparameterchoice',
            options={'ordering': ['parameter__name', 'value'], 'verbose_name': 'Ընտրովի արժեք', 'verbose_name_plural': 'Ընտրովի արժեքներ'},
        ),
        migrations.AlterModelOptions(
            name='importerparametertype',
            options={'ordering': ['name'], 'verbose_name': 'Պարամետրի տեսակ', 'verbose_name_plural': 'Պարամետրերի տեսակներ'},
        ),
        migrations.AlterModelOptions(
            name='importerparametervalue',
            options={'ordering': ['importer__company_name', 'parameter__name'], 'verbose_name': 'Պարամետրի արժեք', 'verbose_name_plural': 'Պարամետրերի արժեքներ'},
        ),
        migrations.AlterModelOptions(
            name='importerprofile',
            options={'ordering': ['-created_at'], 'verbose_name': 'Մատակարար', 'verbose_name_plural': 'Մատակարարներ'},
        ),
        migrations.AlterModelOptions(
            name='importerworkphone',
            options={'verbose_name': 'Աշխատանքային հեռախոսահամար', 'verbose_name_plural': 'Աշխատանքային հեռախոսահամարներ'},
        ),
        migrations.RemoveField(
            model_name='importerprofile',
            name='id_card_number',
        ),
        migrations.AddField(
            model_name='importerprofile',
            name='seo_description',
            field=models.TextField(blank=True, null=True, verbose_name='SEO նկարագրություն'),
        ),
        migrations.AddField(
            model_name='importerprofile',
            name='seo_title',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='SEO վերնագիր'),
        ),
        migrations.AddField(
            model_name='importerprofile',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='importercertificate',
            name='importer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificates', to='accounts.importerprofile', verbose_name='Մատակարար'),
        ),
        migrations.AlterField(
            model_name='importercontract',
            name='importer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contracts', to='accounts.importerprofile', verbose_name='Մատակարար'),
        ),
        migrations.AlterField(
            model_name='importeremployee',
            name='position',
            field=models.CharField(max_length=255, verbose_name='Պաշտոն'),
        ),
        migrations.AlterField(
            model_name='importerparameter',
            name='is_filterable',
            field=models.BooleanField(default=False, verbose_name='Ֆիլտրվող է'),
        ),
        migrations.AlterField(
            model_name='importerparameter',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Անվանում'),
        ),
        migrations.AlterField(
            model_name='importerparameter',
            name='parameter_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parameters', to='accounts.importerparametertype', verbose_name='Պարամետրի տեսակ'),
        ),
        migrations.AlterField(
            model_name='importerparameter',
            name='value_type',
            field=models.CharField(choices=[('text', 'Տեքստ'), ('number', 'Թիվ'), ('choice', 'Ընտրովի'), ('file', 'Ֆայլ'), ('image', 'Նկար'), ('video', 'Վիդեո'), ('boolean', 'Առկա է / Առկա չէ')], default='text', max_length=20, verbose_name='Արժեքի տեսակ'),
        ),
        migrations.AlterField(
            model_name='importerparameterchoice',
            name='parameter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='accounts.importerparameter', verbose_name='Պարամետր'),
        ),
        migrations.AlterField(
            model_name='importerparameterchoice',
            name='value',
            field=models.CharField(max_length=255, verbose_name='Արժեք'),
        ),
        migrations.AlterField(
            model_name='importerparametertype',
            name='name',
            field=models.CharField(max_length=255, unique=True, verbose_name='Պարամետրի տեսակ'),
        ),
        migrations.AlterField(
            model_name='importerparametervalue',
            name='choice_value',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.importerparameterchoice', verbose_name='Ընտրված տարբերակ'),
        ),
        migrations.AlterField(
            model_name='importerparametervalue',
            name='file_value',
            field=models.FileField(blank=True, null=True, upload_to='param_files/', verbose_name='Ֆայլ'),
        ),
        migrations.AlterField(
            model_name='importerparametervalue',
            name='image_value',
            field=models.ImageField(blank=True, null=True, upload_to='param_images/', verbose_name='Նկար'),
        ),
        migrations.AlterField(
            model_name='importerparametervalue',
            name='importer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parameter_values', to='accounts.importerprofile', verbose_name='Մատակարար'),
        ),
        migrations.AlterField(
            model_name='importerparametervalue',
            name='number_value',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Թվային արժեք'),
        ),
        migrations.AlterField(
            model_name='importerparametervalue',
            name='parameter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='importer_values', to='accounts.importerparameter', verbose_name='Պարամետր'),
        ),
        migrations.AlterField(
            model_name='importerparametervalue',
            name='text_value',
            field=models.TextField(blank=True, null=True, verbose_name='Տեքստային արժեք'),
        ),
        migrations.AlterField(
            model_name='importerparametervalue',
            name='video_value',
            field=models.FileField(blank=True, null=True, upload_to='param_videos/', verbose_name='Վիդեո'),
        ),
        migrations.AlterField(
            model_name='importerprofile',
            name='company_name',
            field=models.CharField(max_length=255, verbose_name='Ընկերության անվանում'),
        ),
        migrations.AlterField(
            model_name='importerprofile',
            name='is_verified',
            field=models.BooleanField(default=False, verbose_name='Էլ-հասցեն հաստատված է'),
        ),
        migrations.AlterField(
            model_name='importerprofile',
            name='phone',
            field=models.CharField(max_length=20, verbose_name='Ղեկավարի / հիմնական կոնտակտի հեռախոս'),
        ),
        migrations.AlterField(
            model_name='importerprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='importer_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='importerworkphone',
            name='importer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_phones', to='accounts.importerprofile', verbose_name='Մատակարար'),
        ),
        migrations.AlterUniqueTogether(
            name='importerparametervalue',
            unique_together={('importer', 'parameter')},
        ),
    ]
