# Generated by Django 5.2.7 on 2026-04-14 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0036_alter_importercertificate_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='importerprofile',
            name='google_map_embed',
            field=models.TextField(blank=True, null=True, verbose_name='Google քարտեզ (embed iframe)'),
        ),
    ]
