# Generated by Django 5.2.7 on 2026-04-18 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0037_importerprofile_google_map_embed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='importerprofile',
            name='logo',
            field=models.FileField(blank=True, null=True, upload_to='importer_logos/', verbose_name='Լոգո'),
        ),
    ]
