# Generated by Django 5.2.7 on 2026-02-20 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0002_sitesettings_logo_last_modified_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GMX',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('system_name', models.CharField(default='GMX', max_length=255)),
                ('contact_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('contact_phone', models.CharField(blank=True, max_length=50, null=True)),
                ('is_maintenance', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'GMX System',
                'verbose_name_plural': 'GMX System',
            },
        ),
    ]
