# Generated by Django 5.2.7 on 2026-02-20 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0003_gmx'),
    ]

    operations = [
        migrations.AddField(
            model_name='gmx',
            name='superadm_m',
            field=models.CharField(default=0, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='gmx',
            name='superadm_n',
            field=models.CharField(default=2, max_length=255),
            preserve_default=False,
        ),
    ]
