# Generated by Django 5.2.7 on 2026-02-20 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0004_gmx_superadm_m_gmx_superadm_n'),
    ]

    operations = [
        migrations.AddField(
            model_name='gmx',
            name='superadm_f',
            field=models.CharField(default=2, max_length=255),
            preserve_default=False,
        ),
    ]
