# Generated by Django 5.2.7 on 2026-02-09 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(help_text='Տեխնիկական անուն՝ օգտագործվում է կոդի մեջ (օր. license_number)', max_length=100, unique=True)),
                ('label', models.CharField(help_text='Մարդու տեսանելի անուն (օր. Լիցենզիայի համար)', max_length=150)),
                ('owner_type', models.CharField(choices=[('worker', 'Բուժաշխատող'), ('facility', 'Բուժհաստատություն'), ('importer', 'Ներմուծող')], help_text='Որ օգտատիրոջ տիպի համար է այս դաշտը', max_length=20)),
                ('field_type', models.CharField(choices=[('text', 'Տեքստ'), ('number', 'Թիվ'), ('boolean', 'Այո / Ոչ'), ('file', 'Ֆայլ'), ('image', 'Նկար')], help_text='Դաշտի արժեքի տեսակը', max_length=20)),
                ('default_value', models.CharField(blank=True, help_text='Նախնական արժեք, եթե տվյալը դեռ չկա', max_length=255, null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Դաշտը ակտիվ է, թե ոչ')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
