# Generated by Django 5.2.7 on 2026-02-09 21:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_logic', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomFieldValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.TextField(blank=True, null=True, verbose_name='Արձագանք/Արժեք')),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='values', to='core_logic.customfield', verbose_name='Դաշտ')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_values', to=settings.AUTH_USER_MODEL, verbose_name='Օգտատեր')),
            ],
            options={
                'verbose_name': 'Custom դաշտի արժեք',
                'verbose_name_plural': 'Custom դաշտերի արժեքներ',
                'unique_together': {('field', 'user')},
            },
        ),
    ]
