# Generated by Django 5.2.7 on 2026-02-09 21:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core_logic', '0002_customfieldvalue'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomFieldValue',
        ),
    ]
