# Generated by Django 5.2.7 on 2026-02-09 22:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core_logic', '0003_delete_customfieldvalue'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomField',
        ),
    ]
