# Generated by Django 5.2.7 on 2026-02-22 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_logic', '0006_section_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='title',
            field=models.CharField(max_length=300),
        ),
    ]
