# Generated by Django 5.2.7 on 2026-02-23 11:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_logic', '0008_contentimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subsections', to='core_logic.section'),
        ),
    ]
